### PR TITLE
Added Test_definitions folder under code

### PR DESCRIPTION
**Pull request by Kevsy**
[Reference issue #59 in Commonalities ](https://github.com/camaraproject/Commonalities/issues/59)

Note: this commit suggests

/code/Test_definitions

...however for sub-projects with multiple APIs then the structure may be:

/code/API_defintions/{api_sub_group}/Test_definitions

e..g. /code/API_definitions/Discovery/Test_definitions

### CODE REVIEW

**Comment by FabrizioMoggio** [comment]
@Kevsy considering your proposal for the sub-projects with multiple APIs, then for sub-projects with just one APIs the structure should be:

/code/**API_defintions**/Test_definitions

.....also considering the API_definitions folder.

Or (option 2) the other way around, for sub-projects with multiple APIs then the structure should be:

/code/Test_defintions/{api_sub_group}/.feature

or

/code/Test_defintions/{api_sub_group}/cucumber

I would suggest this second option because if a Developer is used to work in a single API project, he/her expects to find the test folder under /code.

**Comment by MarkusKuemmerle** [comment]
Code only should be in the provider implementation repos, not in the lead repos. The question is if tests are implementation specific or should be implementation independent. I would vote for the last one, then it makes sense to have it as <root>/Test_definitions/ only in the lead repos.

**Comment by Kevsy** [comment]
> Code only should be in the provider implementation repos, not in the lead repos.

Correct, although to avoid confusion in this thread, [Template Lead repository](https://github.com/camaraproject/Template_Lead_Repository) sets the structure `code/API_definitions`  (i.e. /code/is part of the path)- so I think it's fair to have the paths suggested by @FabrizioMoggio above (which include /code/)

> The question is if tests are implementation specific or should be implementation independent. I would vote for the last one, then it makes sense to have it as /Test_definitions/ only in the lead repos.

Yes, I agree

**Comment by Kevsy** [comment]
HI @MarkusKuemmerle - I cannot see a CODEOWNER or Maintainers for Template Lead Repository, which means the PR Cannot be merged. Please can you advise?

**Comment by MarkusKuemmerle** [comment]
In a template we can't have maintainers or code owners, because these would be automatially copied then in the Sub Project repos created with the template. The admins can do the merge / changes.

You only want to add one additional folder for testing, correct? Shall we add this folder to all exisiting Lead Repos too to be consistent with the template?

**Review by hdamker — APPROVED** [review]

**Pull request merged**
